// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgNgOoZt6Y989Gm7Az5OJFsIZhziWASjY',
    appId: '1:920547360785:web:1c4a7d1cce7a5ef78c71b0',
    messagingSenderId: '920547360785',
    projectId: 'arenabet-c8607',
    authDomain: 'arenabet-c8607.firebaseapp.com',
    storageBucket: 'arenabet-c8607.firebasestorage.app',
    measurementId: 'G-QX2VXQMMVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXT2FzokbNw0gK-guYE5c2c57i2wVOslQ',
    appId: '1:920547360785:android:6531fa36f1422d638c71b0',
    messagingSenderId: '920547360785',
    projectId: 'arenabet-c8607',
    storageBucket: 'arenabet-c8607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBomN-_38D_urCYYp41tKTlerhQD0C3mTU',
    appId: '1:920547360785:ios:fbb09bacffbcda928c71b0',
    messagingSenderId: '920547360785',
    projectId: 'arenabet-c8607',
    storageBucket: 'arenabet-c8607.firebasestorage.app',
    iosBundleId: 'com.example.xoxo',
  );
}
